FROM node:24-alpine AS build
WORKDIR /app

ARG VUE_APP_API_URL=http://127.0.0.1:5001
ARG BACKEND_SERVICE_URL=http://127.0.0.1:5001
ARG VITE_BACKEND_SERVICE_URL=http://127.0.0.1:5001
ARG VITE_IOS_API_URL=http://127.0.0.1:5003
ENV VUE_APP_API_URL=$VUE_APP_API_URL \
    BACKEND_SERVICE_URL=$BACKEND_SERVICE_URL \
    VITE_BACKEND_SERVICE_URL=$VITE_BACKEND_SERVICE_URL \
    VITE_IOS_API_URL=$VITE_IOS_API_URL \
    NODE_OPTIONS=--max-old-space-size=4096

COPY ./ui/package.json ./ui/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY ./ui /app
RUN yarn build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx-spa.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
